import 'package:flutter/material.dart';

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          SignIn(),
        ]),
      ),
    );
  }
}

class SignIn extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    double deviceheight = MediaQuery.of(context).size.height;
    double appbarheight = 45;

    double devicewidth = MediaQuery.of(context).size.width;
    return Scaffold(
      body: SingleChildScrollView(
        child: Column(
          children: [
            Container(
              width: devicewidth,
              height: deviceheight,
              // clipBehavior: Clip.antiAlias,
              decoration: BoxDecoration(color: Colors.white),
              child: Stack(
                children: [
                  Positioned(
                    left: 31,
                    top: 467,
                    child: Container(
                      width: 298,
                      height: 31,
                      decoration: BoxDecoration(
                        color: Color(0x00D9D9D9),
                        border: Border(
                          left: BorderSide(color: Color(0xFFDBDCDF)),
                          top: BorderSide(color: Color(0xFFDBDCDF)),
                          right: BorderSide(color: Color(0xFFDBDCDF)),
                          bottom:
                              BorderSide(width: 0.50, color: Color(0xFFDBDCDF)),
                        ),
                      ),
                    ),
                  ),
                  Positioned(
                    left: 31,
                    top: 521,
                    child: Container(
                      width: 298,
                      height: 31,
                      decoration: BoxDecoration(
                        color: Color(0x00D9D9D9),
                        border: Border(
                          left: BorderSide(color: Color(0xFFDBDCDF)),
                          top: BorderSide(color: Color(0xFFDBDCDF)),
                          right: BorderSide(color: Color(0xFFDBDCDF)),
                          bottom:
                              BorderSide(width: 0.50, color: Color(0xFFDBDCDF)),
                        ),
                      ),
                    ),
                  ),
                  Positioned(
                    left: 0,
                    top: -47,
                    child: Container(
                      width: 360,
                      height: 282,
                      decoration: ShapeDecoration(
                        color: Color(0xFF265AE8),
                        shape: RoundedRectangleBorder(
                          borderRadius: BorderRadius.circular(42),
                        ),
                        shadows: [
                          BoxShadow(
                            color: Color(0x3F000000),
                            blurRadius: 4,
                            offset: Offset(0, 4),
                            spreadRadius: 0,
                          )
                        ],
                      ),
                    ),
                  ),
                  Positioned(
                    left: 0,
                    top: 767,
                    child: Container(
                      width: 360,
                      height: 33,
                      decoration: BoxDecoration(color: Colors.white),
                      child: Stack(
                        children: [
                          Positioned(
                            left: 0,
                            top: 15.53,
                            child: Container(width: 360, height: 17.47),
                          ),
                          Positioned(
                            left: 114,
                            top: 20,
                            child: Opacity(
                              opacity: 0.90,
                              child: Container(
                                width: 131,
                                height: 5,
                                decoration: ShapeDecoration(
                                  color: Colors.black,
                                  shape: RoundedRectangleBorder(
                                    borderRadius: BorderRadius.circular(100),
                                  ),
                                ),
                              ),
                            ),
                          ),
                        ],
                      ),
                    ),
                  ),
                  Positioned(
                    left: 56,
                    top: 78,
                    child: SizedBox(
                      width: 248,
                      height: 60,
                      child: Text(
                        'Welcome Back to EduEd',
                        textAlign: TextAlign.center,
                        style: TextStyle(
                          color: Colors.white,
                          fontSize: 24,
                          fontFamily: 'Montserrat',
                          fontWeight: FontWeight.w700,
                        ),
                      ),
                    ),
                  ),
                  Positioned(
                    left: 56,
                    top: 139,
                    child: SizedBox(
                      width: 248,
                      height: 32,
                      child: Text(
                        'Sign in to continue',
                        textAlign: TextAlign.center,
                        style: TextStyle(
                          color: Colors.white,
                          fontSize: 24,
                          fontFamily: 'Montserrat',
                          fontWeight: FontWeight.w400,
                        ),
                      ),
                    ),
                  ),
                  Positioned(
                    left: 56,
                    top: 434,
                    child: SizedBox(
                      width: 248,
                      height: 32,
                      child: Text(
                        'or',
                        textAlign: TextAlign.center,
                        style: TextStyle(
                          color: Colors.black,
                          fontSize: 14,
                          fontFamily: 'Montserrat',
                          fontWeight: FontWeight.w300,
                        ),
                      ),
                    ),
                  ),
                  Positioned(
                    left: 31,
                    top: 273,
                    child: Container(
                      width: 298,
                      height: 50,
                      decoration: ShapeDecoration(
                        color: Color(0xFFEDEEF0),
                        shape: RoundedRectangleBorder(
                            borderRadius: BorderRadius.circular(7)),
                      ),
                    ),
                  ),
                  Positioned(
                    left: 31,
                    top: 357,
                    child: Container(
                      width: 298,
                      height: 50,
                      decoration: ShapeDecoration(
                        color: Color(0xFFEDEEF0),
                        shape: RoundedRectangleBorder(
                            borderRadius: BorderRadius.circular(7)),
                      ),
                    ),
                  ),
                  Positioned(
                    left: 31,
                    top: 609,
                    child: Container(
                      width: 298,
                      height: 50,
                      decoration: ShapeDecoration(
                        color: Color(0xFF265AE8),
                        shape: RoundedRectangleBorder(
                            borderRadius: BorderRadius.circular(7)),
                        shadows: [
                          BoxShadow(
                            color: Color(0x3F000000),
                            blurRadius: 4,
                            offset: Offset(0, 4),
                            spreadRadius: 0,
                          )
                        ],
                      ),
                    ),
                  ),
                  Positioned(
                    left: 104,
                    top: 287,
                    child: SizedBox(
                      width: 152,
                      height: 22,
                      child: Text(
                        'Login with Google',
                        style: TextStyle(
                          color: Colors.black,
                          fontSize: 16,
                          fontFamily: 'Montserrat',
                          fontWeight: FontWeight.w400,
                        ),
                      ),
                    ),
                  ),
                  Positioned(
                    left: 104,
                    top: 371,
                    child: SizedBox(
                      width: 172,
                      height: 22,
                      child: Text(
                        'Login with Facebook',
                        style: TextStyle(
                          color: Colors.black,
                          fontSize: 16,
                          fontFamily: 'Montserrat',
                          fontWeight: FontWeight.w400,
                        ),
                      ),
                    ),
                  ),
                  Positioned(
                    left: 94,
                    top: 623,
                    child: SizedBox(
                      width: 172,
                      height: 22,
                      child: Text(
                        'Log in',
                        textAlign: TextAlign.center,
                        style: TextStyle(
                          color: Colors.white,
                          fontSize: 16,
                          fontFamily: 'Montserrat',
                          fontWeight: FontWeight.w800,
                        ),
                      ),
                    ),
                  ),
                  Positioned(
                    left: 93,
                    top: 679,
                    child: SizedBox(
                      width: 172,
                      height: 22,
                      child: Text(
                        'Forgot Password',
                        textAlign: TextAlign.center,
                        style: TextStyle(
                          color: Color(0xFF265AE8),
                          fontSize: 12,
                          fontFamily: 'Montserrat',
                          fontWeight: FontWeight.w400,
                        ),
                      ),
                    ),
                  ),
                  Positioned(
                    left: 36,
                    top: 471,
                    child: SizedBox(
                      width: 248,
                      height: 22,
                      child: Text(
                        'username',
                        style: TextStyle(
                          color: Color(0xFF70747E),
                          fontSize: 16,
                          fontFamily: 'Montserrat',
                          fontWeight: FontWeight.w400,
                        ),
                      ),
                    ),
                  ),
                  Positioned(
                    left: 31,
                    top: 555,
                    child: SizedBox(
                      width: 248,
                      height: 22,
                      child: Text(
                        'password is invalid',
                        style: TextStyle(
                          color: Color(0xFFFF0000),
                          fontSize: 10,
                          fontFamily: 'Montserrat',
                          fontWeight: FontWeight.w400,
                        ),
                      ),
                    ),
                  ),
                  Positioned(
                    left: 36,
                    top: 525,
                    child: SizedBox(
                      width: 248,
                      height: 22,
                      child: Text(
                        '********************',
                        style: TextStyle(
                          color: Color(0xFF70747E),
                          fontSize: 16,
                          fontFamily: 'Montserrat',
                          fontWeight: FontWeight.w400,
                        ),
                      ),
                    ),
                  ),
                  Positioned(
                    left: 301,
                    top: 525,
                    child: Container(
                      width: 24,
                      height: 18,
                      child: Stack(children: []),
                    ),
                  ),
                  Positioned(
                    left: 56,
                    top: 284,
                    child: Container(
                      width: 28,
                      height: 28,
                      decoration: BoxDecoration(
                        image: DecorationImage(
                          image:
                              NetworkImage("https://via.placeholder.com/28x28"),
                          fit: BoxFit.fill,
                        ),
                      ),
                    ),
                  ),
                  Positioned(
                    left: 56,
                    top: 368,
                    child: Container(
                      width: 28,
                      height: 28,
                      child: Stack(children: []),
                    ),
                  ),
                  Positioned(
                    left: 67,
                    top: 721,
                    child: SizedBox(
                      width: 225,
                      height: 22,
                      child: Text.rich(
                        TextSpan(
                          children: [
                            TextSpan(
                              text: 'Didn’t have a account ',
                              style: TextStyle(
                                color: Colors.black,
                                fontSize: 12,
                                fontFamily: 'Montserrat',
                                fontWeight: FontWeight.w400,
                              ),
                            ),
                            TextSpan(
                              text: 'Sign up',
                              style: TextStyle(
                                color: Color(0xFF265AE8),
                                fontSize: 12,
                                fontFamily: 'Montserrat',
                                fontWeight: FontWeight.w400,
                              ),
                            ),
                            TextSpan(
                              text: ' here',
                              style: TextStyle(
                                color: Colors.black,
                                fontSize: 12,
                                fontFamily: 'Montserrat',
                                fontWeight: FontWeight.w400,
                              ),
                            ),
                          ],
                        ),
                        textAlign: TextAlign.center,
                      ),
                    ),
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }
}
